application: forma-api
version: beta
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

handlers:

- url: /api.*
  script: forma.api.handler

- url: /admin/.*
  script: admin.handler
